name: CI-pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the codebase
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Lint the Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - name: Lint the source code
        uses: Silleellie/pylint-github-action@v2.1
        with:
          lint-path: |
            mysite
            polls
            manage.py
          requirements-path: requirements.txt
          readme-path: README.md
          python-version: 3.11  # python version which will lint the package
