name: CI-pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the codebase
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Lint the Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
