name: CI-pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the codebase
        uses: actions/checkout@v4
        with:
          ref: dev
