name: CI-pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the codebase
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Lint the Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - name: Lint the source code
        uses: Silleellie/pylint-github-action@v2.1
        with:
          lint-path: |
            mysite
            polls
            manage.py
          requirements-path: requirements.txt
          readme-path: README.md
          python-version: 3.11  # python version which will lint the package
      - name: Notify in telegram about fail
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      - name: Check fail
        run: echo "Unreachable"
