name: Deploy on server
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build and push Docker image]
    types:
      - completed


jobs:
  Deploy:
    name: Trigger Jenkins pipeline by cURL
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Jenkins jobs
      run: |
        curl -X POST -I \
        -u ${{ vars.JENKINS_USERNAME }}:${{ secrets.JENKINS_TOKEN }} \
        https://ci.saccada.xyz//job/deploy-django-application/build
